name: Heroku Deploy
on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install Dependencies
              run: npm ci --prefix web worker

            - name: Build
              run: npm run build:all

            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
              env:
                  HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
                  HD_CLIENT_ID: ${{secrets.CLIENT_ID}}
                  HD_GUILD_ID: ${{secrets.CLIENT_ID}}
                  HD_MONGODB_URI: ${{secrets.MONGODB_URI}}
