name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        # env: ${{secrets.ENV}}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies and run web tests
              run: |
                  npm install --prefix web
                  npm run test:web

            - name: Install dependencies and run worker tests
              run: |
                  npm install --prefix worker
                  npm run test:worker
